<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IP7TE20" failures="1" tests="1" name="Master(failed)" time="31.232" errors="0" timestamp="2025-06-08T18:12:30 IST">
  <testcase classname="com.parabank.tests.TC009_VerifyCaseSensitivityInLoginTest" name="VerifyCaseSensitivityInLoginTest" time="3.588">
    <failure type="java.lang.AssertionError" message="expected [The username and password could not be verified.] but found [An internal error has occurred and has been logged.]">
      <![CDATA[java.lang.AssertionError: expected [The username and password could not be verified.] but found [An internal error has occurred and has been logged.]
at com.parabank.tests.TC009_VerifyCaseSensitivityInLoginTest.VerifyCaseSensitivityInLoginTest(TC009_VerifyCaseSensitivityInLoginTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyCaseSensitivityInLoginTest -->
</testsuite> <!-- Master(failed) -->
